name: smoke-test
on:
  push:
    branches: [ master ]

    pull_request:
      branches:
        - master

    workflow_dispatch:
    
jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
      - name: get sources
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        
      - name: restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal # --collect:"XPlat code coverage" --settings coverlet.runsettings
